# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odometr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_mileage', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('yearly_mileage', models.PositiveIntegerField()),
                ('end_date', models.DateTimeField(verbose_name='date ends')),
            ],
        ),
        migrations.DeleteModel(
            name='Checkpoint',
        ),
    ]
