# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odometr', '0003_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='My Car', max_length=50),
            preserve_default=False,
        ),
    ]
